### ISSUE TITLE
Mise en place Rocket Chat

### ISSUE THREAD

**Issue by nowaiiNN** [sentaku-io/sentaku-io-messenger#3]
- [x] Installation environnement de dev
- [x] Installation environnement de recette
- [x] Création user technique

**Comment by nowaiiNN** [comment]
- [ ] Création user technique

**Comment by Delwaulle** [comment]
https://rocket.chat/docs/administrator-guides/create-the-first-admin/
https://github.com/RocketChat/docs/tree/master/administrator-guides
